# -*- coding: utf-8 -*-
"""Diez dominios de app de ejemplo. Son EJEMPLOS: el equipo puede proponer el suyo."""
D = [
dict(id="01", slug="ruta-limpia", nombre="Ruta Limpia", tag="Recojo de residuos sólidos",
 problema="En los distritos de la periferia el camión recolector no tiene horario fijo. La gente saca la basura cuando cree que va a pasar, y si no pasa queda en la vereda hasta el día siguiente. Nadie sabe dónde está el camión.",
 segmento="Vecinos de un distrito de 40 000 habitantes, y los operarios del camión",
 por_que_movil="El vecino necesita un aviso **cuando el camión está a diez minutos de su cuadra**. Eso exige notificación push y posición en tiempo real: una página web no avisa a nadie.",
 movil=["Notificaciones push por proximidad","Ubicación en segundo plano del vehículo","Mapa con la ruta en curso"],
 permisos=["Ubicación aproximada y precisa","Ubicación en segundo plano (solo la app del operario)","Notificaciones"],
 datos=["Dirección aproximada del vecino","Token de notificación"], sensibles="Media",
 entidades=["Ruta","Vehículo","Punto de recojo","Reporte","Aviso"],
 sprints=["Autenticación, catálogo de rutas y mapa base","Posición del vehículo y ruta en curso","Notificación por proximidad","Reporte de punto no recogido con foto","Historial y panel del operario"]),

dict(id="02", slug="mi-turno", nombre="Mi Turno", tag="Turnos en establecimiento de salud",
 problema="En el centro de salud la gente hace cola desde las cinco de la mañana para conseguir un cupo que se agota a las siete. Muchos viajan desde el valle para volverse sin atención.",
 segmento="Pacientes de un centro de salud del primer nivel y su personal de admisión",
 por_que_movil="El paciente necesita saber **desde su casa** si le queda cupo, y que le avisen cuando falten tres turnos para el suyo. Sin notificación, la cola física no desaparece.",
 movil=["Notificaciones push de turno próximo","Funcionamiento sin conexión para el carné digital","Cámara para el documento de identidad"],
 permisos=["Notificaciones","Cámara"],
 datos=["Nombre y documento de identidad","Motivo de consulta","Historial de turnos"], sensibles="**Alta — dato de salud**",
 entidades=["Paciente","Turno","Consultorio","Profesional","Aviso"],
 sprints=["Autenticación y registro del paciente","Consulta de cupos disponibles por consultorio","Reserva y cancelación de turno","Aviso de turno próximo y carné sin conexión","Panel de admisión y reprogramación"]),

dict(id="03", slug="carga-sur", nombre="Carga Sur", tag="Transporte de carga Tacna–Ilo",
 problema="El transportista independiente consigue carga por llamadas y grupos de WhatsApp. Vuelve vacío la mitad de los viajes porque no se entera de la carga de retorno hasta que ya salió.",
 segmento="Transportistas independientes y pequeños generadores de carga del corredor sur",
 por_que_movil="La carga de retorno se decide **en la carretera**, no en una oficina. Necesita ubicación, aviso inmediato y funcionar con señal intermitente.",
 movil=["Ubicación para ofertar carga cercana","Notificaciones push de nueva carga en ruta","Persistencia sin conexión en tramos sin señal"],
 permisos=["Ubicación precisa","Notificaciones","Cámara para la guía de remisión"],
 datos=["Placa y licencia del conductor","Ubicación del vehículo","Datos del generador de carga"], sensibles="Media",
 entidades=["Viaje","Carga","Transportista","Oferta","Guía"],
 sprints=["Autenticación y perfil de transportista","Publicación y búsqueda de carga","Ofertas y aceptación","Seguimiento del viaje y guía con foto","Historial, calificación y panel del generador"]),

dict(id="04", slug="riego-justo", nombre="Riego Justo", tag="Control de turnos de riego",
 problema="En la comisión de regantes el turno de agua se anota en un cuaderno. Los conflictos por minutos de riego son constantes y no hay forma de probar quién regó cuándo.",
 segmento="Regantes de una comisión de 300 usuarios y el tomero que asigna los turnos",
 por_que_movil="El registro se hace **en la parcela, sin señal**. Exige funcionamiento sin conexión con sincronización posterior: es el caso donde una web es directamente inviable.",
 movil=["Funcionamiento sin conexión con sincronización diferida","Cámara para el estado del canal","Ubicación para validar que el registro se hizo en la parcela"],
 permisos=["Cámara","Ubicación precisa","Almacenamiento"],
 datos=["Nombre del regante","Ubicación de la parcela","Horas de riego consumidas"], sensibles="Baja",
 entidades=["Regante","Parcela","Turno","Registro de riego","Incidencia"],
 sprints=["Autenticación y padrón de regantes","Calendario de turnos","Registro de riego sin conexión","Sincronización y resolución de conflictos","Reportes de consumo e incidencias"]),

dict(id="05", slug="mi-farmacia", nombre="Mi Farmacia", tag="Inventario y vencimientos de botica",
 problema="La botica de barrio pierde dinero por productos vencidos que nadie revisó y por quiebres de stock que se descubren cuando el cliente ya se fue.",
 segmento="Boticas independientes de uno a tres locales",
 por_que_movil="El conteo se hace **en el anaquel, con el producto en la mano**. Exige lector de código de barras por cámara, que en el móvil es inmediato.",
 movil=["Lectura de código de barras con la cámara","Notificación de vencimiento próximo","Conteo sin conexión"],
 permisos=["Cámara","Notificaciones"],
 datos=["Inventario y precios","Datos del titular"], sensibles="Baja",
 entidades=["Producto","Lote","Movimiento","Alerta","Local"],
 sprints=["Autenticación y catálogo de productos","Lectura de código de barras e ingreso de lotes","Movimientos y stock por local","Alertas de vencimiento y quiebre","Reportes y cierre de inventario"]),

dict(id="06", slug="ruta-segura", nombre="Ruta Segura", tag="Transporte escolar",
 problema="Los padres no saben si el movilidad escolar recogió a su hijo ni por dónde va. Cuando llaman, el conductor está manejando y no contesta.",
 segmento="Padres de familia, conductores de movilidad escolar y el colegio",
 por_que_movil="El padre necesita la confirmación **en el momento del recojo**, y el conductor no puede operar nada complejo mientras maneja. Push y ubicación en segundo plano son obligatorios.",
 movil=["Ubicación en segundo plano del vehículo","Notificación de recojo y llegada","Registro con un solo toque para el conductor"],
 permisos=["Ubicación en segundo plano","Notificaciones"],
 datos=["**Datos de menores de edad**","Ubicación del vehículo","Dirección de recojo"], sensibles="**Muy alta — menores de edad**",
 entidades=["Estudiante","Vehículo","Ruta","Evento de recojo","Apoderado"],
 sprints=["Autenticación por rol y padrón de estudiantes","Ruta y mapa en vivo","Registro de recojo y llegada","Notificaciones a los apoderados","Historial, incidencias y panel del colegio"]),

dict(id="07", slug="reporta-tacna", nombre="Reporta Tacna", tag="Reportes ciudadanos al municipio",
 problema="El vecino reporta un poste caído o un desagüe roto por teléfono, y no vuelve a saber nada. La municipalidad recibe reportes duplicados sin ubicación exacta.",
 segmento="Vecinos de un distrito y el área de servicios públicos del municipio",
 por_que_movil="El reporte se hace **frente al problema**: foto y coordenada exacta en el momento. Un formulario web produce reportes sin ubicación y sin evidencia.",
 movil=["Cámara con la coordenada del reporte","Ubicación precisa","Notificación de cambio de estado"],
 permisos=["Cámara","Ubicación precisa","Notificaciones"],
 datos=["Nombre y contacto del vecino","Ubicación del reporte","Fotografías"], sensibles="Media",
 entidades=["Reporte","Categoría","Estado","Ciudadano","Cuadrilla"],
 sprints=["Autenticación y catálogo de categorías","Reporte con foto y ubicación","Estado y seguimiento del reporte","Detección de duplicados por cercanía","Panel de cuadrilla y cierre con evidencia"]),

dict(id="08", slug="patrimonio-vivo", nombre="Patrimonio Vivo", tag="Guía turística de patrimonio",
 problema="El visitante llega al centro histórico sin saber qué está viendo. Los paneles informativos están deteriorados y no hay guía disponible fuera de temporada.",
 segmento="Turistas nacionales y chilenos que visitan el centro histórico de Tacna",
 por_que_movil="El contenido debe estar disponible **caminando y sin datos móviles**, porque el visitante extranjero suele no tener plan local. Exige descarga previa y ubicación.",
 movil=["Contenido descargado para uso sin conexión","Ubicación para detectar el punto cercano","Notificación al acercarse a un hito"],
 permisos=["Ubicación precisa","Almacenamiento","Notificaciones"],
 datos=["Recorridos del visitante","Idioma preferido"], sensibles="Baja",
 entidades=["Hito","Recorrido","Contenido","Visita","Idioma"],
 sprints=["Catálogo de hitos y contenido base","Descarga para uso sin conexión","Mapa y detección de proximidad","Recorridos guiados y multilenguaje","Estadísticas de visita y panel de contenidos"]),

dict(id="09", slug="campo-presente", nombre="Campo Presente", tag="Asistencia de personal de campo",
 problema="La empresa agrícola controla la asistencia de 380 trabajadores de campaña con listas en papel. El pago se calcula sobre datos que nadie puede verificar.",
 segmento="Empresas agroexportadoras con personal eventual en campo",
 por_que_movil="La marcación ocurre **en el fundo, sin señal y sin computadora**. Exige registro sin conexión, ubicación validada y evidencia fotográfica.",
 movil=["Registro sin conexión con sincronización posterior","Ubicación para validar el punto de marcación","Cámara para la evidencia de cuadrilla"],
 permisos=["Ubicación precisa","Cámara","Almacenamiento"],
 datos=["Nombre y documento del trabajador","Ubicación de la marcación","Fotografía de la cuadrilla"], sensibles="**Alta — dato laboral y biométrico si se usa rostro**",
 entidades=["Trabajador","Cuadrilla","Marcación","Labor","Jornada"],
 sprints=["Autenticación y padrón de trabajadores","Marcación sin conexión","Sincronización y validación por ubicación","Asignación de labores y cuadrillas","Reporte de jornadas y exportación para planilla"]),

dict(id="10", slug="frontera-clara", nombre="Frontera Clara", tag="Trámite de paso de frontera",
 problema="Quien cruza a Arica no sabe cuánto demora el control migratorio ese día, ni qué puede llevar sin declarar. La información oficial está dispersa en varios portales.",
 segmento="Residentes de Tacna que cruzan con frecuencia y visitantes ocasionales",
 por_que_movil="La consulta se hace **en el trayecto o en la cola**, con señal pobre y a veces en roaming. Exige contenido sin conexión y avisos.",
 movil=["Contenido normativo sin conexión","Notificación de cambio de tiempos de espera","Cámara para guardar el comprobante"],
 permisos=["Notificaciones","Cámara","Almacenamiento"],
 datos=["Documento de viaje del usuario","Historial de cruces"], sensibles="Media",
 entidades=["Cruce","Tiempo de espera","Regla aduanera","Comprobante","Aviso"],
 sprints=["Catálogo de reglas y consulta sin conexión","Tiempos de espera por control","Registro de cruces del usuario","Avisos de cambio y comprobantes","Panel de estadísticas y validación de contenido"]),
]
