# -*- coding: utf-8 -*-
"""Vocabulario propio de cada dominio: roles, plurales y razón de cada capacidad móvil."""
V = {
"01": dict(rol="vecino", admin="operario del camión", obj="punto de recojo", objp="puntos de recojo",
  reg="reporte", regp="reportes", panel="rutas y reportes", evento="el camión esté a diez minutos de su cuadra",
  razones={"Notificaciones push por proximidad":"Sin aviso previo, el vecino saca la basura a ciegas y el problema no se resuelve",
           "Ubicación en segundo plano del vehículo":"La posición del camión debe seguir enviándose con la app minimizada durante toda la ruta",
           "Mapa con la ruta en curso":"Ver el avance real es lo que permite decidir cuándo bajar los residuos"}),
"02": dict(rol="paciente", admin="personal de admisión", obj="consultorio", objp="consultorios",
  reg="turno", regp="turnos", panel="turnos del día", evento="falten tres turnos para el suyo",
  razones={"Notificaciones push de turno próximo":"Es lo que sustituye a la cola física desde las cinco de la mañana",
           "Funcionamiento sin conexión para el carné digital":"El paciente debe poder mostrar su turno aunque no tenga datos en el establecimiento",
           "Cámara para el documento de identidad":"Evita digitar mal el número de documento en la afiliación"}),
"03": dict(rol="transportista", admin="generador de carga", obj="carga", objp="cargas",
  reg="viaje", regp="viajes", panel="cargas publicadas", evento="aparezca carga de retorno en su ruta",
  razones={"Ubicación para ofertar carga cercana":"La carga de retorno solo sirve si está sobre la ruta que ya va a recorrer",
           "Notificaciones push de nueva carga en ruta":"La decisión se toma en carretera, en minutos, no revisando una web",
           "Persistencia sin conexión en tramos sin señal":"El corredor Tacna–Ilo tiene tramos largos sin cobertura"}),
"04": dict(rol="regante", admin="tomero", obj="turno de riego", objp="turnos de riego",
  reg="registro de riego", regp="registros de riego", panel="consumo por parcela", evento="se acerque su turno de riego",
  razones={"Funcionamiento sin conexión con sincronización diferida":"En la parcela no hay señal: si la app exige red, no sirve",
           "Cámara para el estado del canal":"La foto con fecha es la prueba que hoy no existe en el cuaderno",
           "Ubicación para validar que el registro se hizo en la parcela":"Impide registrar un riego desde la casa"}),
"05": dict(rol="responsable de local", admin="titular de la botica", obj="producto", objp="productos",
  reg="movimiento", regp="movimientos", panel="stock y vencimientos", evento="un lote esté por vencer",
  razones={"Lectura de código de barras con la cámara":"El conteo se hace con el producto en la mano, frente al anaquel",
           "Notificación de vencimiento próximo":"El vencido se pierde porque nadie lo revisa a tiempo",
           "Conteo sin conexión":"El almacén suele ser el punto de peor señal del local"}),
"06": dict(rol="apoderado", admin="coordinador del colegio", obj="estudiante", objp="estudiantes",
  reg="evento de recojo", regp="eventos de recojo", panel="rutas y recojos del día", evento="su hijo sea recogido o llegue al colegio",
  razones={"Ubicación en segundo plano del vehículo":"La ruta dura 40 minutos con la app minimizada; sin segundo plano no hay seguimiento",
           "Notificación de recojo y llegada":"Es la confirmación que hoy el padre intenta conseguir llamando al conductor que va manejando",
           "Registro con un solo toque para el conductor":"Cualquier interfaz compleja al volante es un riesgo de seguridad vial"}),
"07": dict(rol="vecino", admin="jefe de cuadrilla", obj="categoría de reporte", objp="categorías de reporte",
  reg="reporte", regp="reportes", panel="reportes por estado y zona", evento="cambie el estado de su reporte",
  razones={"Cámara con la coordenada del reporte":"Foto y coordenada juntas son lo que convierte una queja en un caso atendible",
           "Ubicación precisa":"Sin coordenada exacta la cuadrilla no encuentra el poste ni el desagüe",
           "Notificación de cambio de estado":"El vecino deja de reportar cuando nunca sabe qué pasó con lo anterior"}),
"08": dict(rol="visitante", admin="gestor de contenidos", obj="hito", objp="hitos",
  reg="visita", regp="visitas", panel="visitas por hito y recorrido", evento="se acerque a un hito del recorrido",
  razones={"Contenido descargado para uso sin conexión":"El visitante chileno suele no tener plan de datos peruano",
           "Ubicación para detectar el punto cercano":"El contenido debe aparecer solo, caminando, sin buscar nada",
           "Notificación al acercarse a un hito":"Es lo que reemplaza al panel informativo deteriorado"}),
"09": dict(rol="supervisor de cuadrilla", admin="jefe de campo", obj="trabajador", objp="trabajadores",
  reg="marcación", regp="marcaciones", panel="jornadas por cuadrilla", evento="una cuadrilla no haya marcado a la hora prevista",
  razones={"Registro sin conexión con sincronización posterior":"El fundo no tiene cobertura y la marcación no puede esperar",
           "Ubicación para validar el punto de marcación":"Es lo que hace verificable un dato del que depende el pago",
           "Cámara para la evidencia de cuadrilla":"Sustituye la lista en papel que hoy nadie puede auditar"}),
"10": dict(rol="usuario frecuente", admin="validador de contenido", obj="regla aduanera", objp="reglas aduaneras",
  reg="cruce", regp="cruces", panel="tiempos y cruces registrados", evento="cambien los tiempos de espera del control",
  razones={"Contenido normativo sin conexión":"En la cola o en roaming no hay forma de consultar un portal",
           "Notificación de cambio de tiempos de espera":"El dato solo sirve si llega antes de salir de casa",
           "Cámara para guardar el comprobante":"El comprobante en papel se pierde y se necesita en el retorno"}),
}
